### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jubianchi** [atoum/json-schema-extension#7]
We should have a license and it should be the same as the atoum/atoum repository

* [ ] a `LICENSE` file: it should be the same as the atoum/atoum repository but every mention to "Frédéric Hardy" must be replaced with "atoum contributors"
* [ ] in the `composer.json` file (`BSD-3-Clause`)
* [ ] in the  `README.md` file: a dedicated section (see [here](https://github.com/atoum/blackfire-extension/blob/master/README.md#licence) for an example)

**Comment by Kerumen** [comment]
I can do this! 👍

**Comment by jubianchi** [comment]
@Kerumen go ahead ;)

**Comment by Kerumen** [comment]
@jubianchi I'll wait until 1st October so it counts towards my score ;)

**Comment by Kerumen** [comment]
Nice.
